Hw5
mkapry/2018-FS-21-Frontend-Kaprielova pull request #4
Opened 2018-11-15 18:58 UTC by mkapry

Немного посмотрела React, сделала маленькую формочку создания блога

2018-11-18 06:32 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/48669391-c8784a80-eb14-11e8-8077-b45182e3cd4a.png)
Этого мало, нужно восстановить все функции с предыдущих ДЗ, включая отправку данных на сервер.

2018-11-25 11:46 UTC, martinkomitsky commented
@mkapry по этому комменту будут правки?
>Этого мало, нужно восстановить все функции с предыдущих ДЗ, включая отправку данных на сервер.

2018-11-25 14:17 UTC, mkapry commented
Да

2018-11-25 15:45 UTC, mkapry commented
@martinkomitsky, это окончательный вариант

2018-11-26 09:49 UTC, martinkomitsky approved these changes

2018-11-26 09:50 UTC, martinkomitsky commented
за тебя проставил зависимости в package.json  для твоих пакетов, не забывай это делать. Помимо этого, у меня не сработала твоя drag&drop функция, картинки там не показываются

2018-11-26 09:50 UTC, merged

2018-11-26 09:50 UTC, martinkomitsky commented
5