Hw6
mkapry/2018-FS-21-Frontend-Kaprielova pull request #5
Opened 2018-11-26 09:09 UTC by mkapry

Дз 6

2018-11-26 09:52 UTC, martinkomitsky requested changes
А теперь, тебя тут ждет боль в виде конфликта, так как ты начала делать дз 6 от мастера, а не от ветки дз 5. Конфкикты нужно починить

2018-11-26 17:52 UTC, mkapry commented
@martinkomitsky, я поправила, можно проверять

2018-11-29 17:47 UTC, martinkomitsky approved these changes

2018-11-29 17:47 UTC, martinkomitsky commented on src/containers/Welcome/Welcome.js
> +                   handleChange = {this.handleInput}
тут должно быть `onChange`, я так понимаю

2018-11-29 17:47 UTC, martinkomitsky commented
@mkapry Исправить замечание в след ДЗ. 5

2018-11-29 17:48 UTC, merged